# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Qt\Qt5.12\6.4.0\Src\qtbase\src\plugins\sqldrivers

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Qt\Qt5.12\6.4.0\Src\qtbase\src\plugins\sqldrivers

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	"C:\Program Files\CMake\bin\ctest.exe" --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Devel\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Qt\Qt5.12\6.4.0\Src\qtbase\src\plugins\sqldrivers\CMakeFiles C:\Qt\Qt5.12\6.4.0\Src\qtbase\src\plugins\sqldrivers\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Qt\Qt5.12\6.4.0\Src\qtbase\src\plugins\sqldrivers\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named QPSQLDriverPlugin

# Build rule for target.
QPSQLDriverPlugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 QPSQLDriverPlugin
.PHONY : QPSQLDriverPlugin

# fast build rule for target.
QPSQLDriverPlugin/fast:
	$(MAKE) $(MAKESILENT) -f psql\CMakeFiles\QPSQLDriverPlugin.dir\build.make psql/CMakeFiles/QPSQLDriverPlugin.dir/build
.PHONY : QPSQLDriverPlugin/fast

#=============================================================================
# Target rules for targets named qt_internal_plugins

# Build rule for target.
qt_internal_plugins: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 qt_internal_plugins
.PHONY : qt_internal_plugins

# fast build rule for target.
qt_internal_plugins/fast:
	$(MAKE) $(MAKESILENT) -f psql\CMakeFiles\qt_internal_plugins.dir\build.make psql/CMakeFiles/qt_internal_plugins.dir/build
.PHONY : qt_internal_plugins/fast

#=============================================================================
# Target rules for targets named qsqlpsql

# Build rule for target.
qsqlpsql: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 qsqlpsql
.PHONY : qsqlpsql

# fast build rule for target.
qsqlpsql/fast:
	$(MAKE) $(MAKESILENT) -f psql\CMakeFiles\qsqlpsql.dir\build.make psql/CMakeFiles/qsqlpsql.dir/build
.PHONY : qsqlpsql/fast

#=============================================================================
# Target rules for targets named QPSQLDriverPlugin_autogen

# Build rule for target.
QPSQLDriverPlugin_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 QPSQLDriverPlugin_autogen
.PHONY : QPSQLDriverPlugin_autogen

# fast build rule for target.
QPSQLDriverPlugin_autogen/fast:
	$(MAKE) $(MAKESILENT) -f psql\CMakeFiles\QPSQLDriverPlugin_autogen.dir\build.make psql/CMakeFiles/QPSQLDriverPlugin_autogen.dir/build
.PHONY : QPSQLDriverPlugin_autogen/fast

#=============================================================================
# Target rules for targets named QMYSQLDriverPlugin

# Build rule for target.
QMYSQLDriverPlugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 QMYSQLDriverPlugin
.PHONY : QMYSQLDriverPlugin

# fast build rule for target.
QMYSQLDriverPlugin/fast:
	$(MAKE) $(MAKESILENT) -f mysql\CMakeFiles\QMYSQLDriverPlugin.dir\build.make mysql/CMakeFiles/QMYSQLDriverPlugin.dir/build
.PHONY : QMYSQLDriverPlugin/fast

#=============================================================================
# Target rules for targets named qsqlmysql

# Build rule for target.
qsqlmysql: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 qsqlmysql
.PHONY : qsqlmysql

# fast build rule for target.
qsqlmysql/fast:
	$(MAKE) $(MAKESILENT) -f mysql\CMakeFiles\qsqlmysql.dir\build.make mysql/CMakeFiles/qsqlmysql.dir/build
.PHONY : qsqlmysql/fast

#=============================================================================
# Target rules for targets named QMYSQLDriverPlugin_autogen

# Build rule for target.
QMYSQLDriverPlugin_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 QMYSQLDriverPlugin_autogen
.PHONY : QMYSQLDriverPlugin_autogen

# fast build rule for target.
QMYSQLDriverPlugin_autogen/fast:
	$(MAKE) $(MAKESILENT) -f mysql\CMakeFiles\QMYSQLDriverPlugin_autogen.dir\build.make mysql/CMakeFiles/QMYSQLDriverPlugin_autogen.dir/build
.PHONY : QMYSQLDriverPlugin_autogen/fast

#=============================================================================
# Target rules for targets named QODBCDriverPlugin

# Build rule for target.
QODBCDriverPlugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 QODBCDriverPlugin
.PHONY : QODBCDriverPlugin

# fast build rule for target.
QODBCDriverPlugin/fast:
	$(MAKE) $(MAKESILENT) -f odbc\CMakeFiles\QODBCDriverPlugin.dir\build.make odbc/CMakeFiles/QODBCDriverPlugin.dir/build
.PHONY : QODBCDriverPlugin/fast

#=============================================================================
# Target rules for targets named qsqlodbc

# Build rule for target.
qsqlodbc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 qsqlodbc
.PHONY : qsqlodbc

# fast build rule for target.
qsqlodbc/fast:
	$(MAKE) $(MAKESILENT) -f odbc\CMakeFiles\qsqlodbc.dir\build.make odbc/CMakeFiles/qsqlodbc.dir/build
.PHONY : qsqlodbc/fast

#=============================================================================
# Target rules for targets named QODBCDriverPlugin_autogen

# Build rule for target.
QODBCDriverPlugin_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 QODBCDriverPlugin_autogen
.PHONY : QODBCDriverPlugin_autogen

# fast build rule for target.
QODBCDriverPlugin_autogen/fast:
	$(MAKE) $(MAKESILENT) -f odbc\CMakeFiles\QODBCDriverPlugin_autogen.dir\build.make odbc/CMakeFiles/QODBCDriverPlugin_autogen.dir/build
.PHONY : QODBCDriverPlugin_autogen/fast

#=============================================================================
# Target rules for targets named QSQLiteDriverPlugin

# Build rule for target.
QSQLiteDriverPlugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 QSQLiteDriverPlugin
.PHONY : QSQLiteDriverPlugin

# fast build rule for target.
QSQLiteDriverPlugin/fast:
	$(MAKE) $(MAKESILENT) -f sqlite\CMakeFiles\QSQLiteDriverPlugin.dir\build.make sqlite/CMakeFiles/QSQLiteDriverPlugin.dir/build
.PHONY : QSQLiteDriverPlugin/fast

#=============================================================================
# Target rules for targets named qsqlite

# Build rule for target.
qsqlite: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 qsqlite
.PHONY : qsqlite

# fast build rule for target.
qsqlite/fast:
	$(MAKE) $(MAKESILENT) -f sqlite\CMakeFiles\qsqlite.dir\build.make sqlite/CMakeFiles/qsqlite.dir/build
.PHONY : qsqlite/fast

#=============================================================================
# Target rules for targets named QSQLiteDriverPlugin_autogen

# Build rule for target.
QSQLiteDriverPlugin_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 QSQLiteDriverPlugin_autogen
.PHONY : QSQLiteDriverPlugin_autogen

# fast build rule for target.
QSQLiteDriverPlugin_autogen/fast:
	$(MAKE) $(MAKESILENT) -f sqlite\CMakeFiles\QSQLiteDriverPlugin_autogen.dir\build.make sqlite/CMakeFiles/QSQLiteDriverPlugin_autogen.dir/build
.PHONY : QSQLiteDriverPlugin_autogen/fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... test
	@echo ... QMYSQLDriverPlugin_autogen
	@echo ... QODBCDriverPlugin_autogen
	@echo ... QPSQLDriverPlugin_autogen
	@echo ... QSQLiteDriverPlugin_autogen
	@echo ... qsqlite
	@echo ... qsqlmysql
	@echo ... qsqlodbc
	@echo ... qsqlpsql
	@echo ... qt_internal_plugins
	@echo ... QMYSQLDriverPlugin
	@echo ... QODBCDriverPlugin
	@echo ... QPSQLDriverPlugin
	@echo ... QSQLiteDriverPlugin
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

